name: ossf-scorecard

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

permissions: read-all

jobs:

  analysis:
    name: analysis
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af # v2.1.3
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
