name: Publish to Maven Central

on:
  workflow_dispatch:

permissions: read-all

jobs:
  publish-to-maven-central:
    name: Publish to Maven Central
    continue-on-error: true
    environment: PublishToMavenCentral
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Trigger Gradle publishing task
        run: ./gradlew publishReleasePublicationToMavenCentralRepository -Ppublish.repo.credentials.username=${{ secrets.MAVEN_CENTRAL_USERNAME }} -Ppublish.repo.credentials.password=${{ secrets.MAVEN_CENTRAL_PASSWORD }} -PsigningInMemoryKey="${{ secrets.SIGNING_IN_MEMORY_KEY }}" -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}"

      # More info on this step available at:
      # https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#1-modify-your-ci-script
      - name: Sync with Maven Central Repository
        run: |
          uploadUrl = $(echo "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/${{ vars.MAVEN_CENTRAL_NAMESPACE }}")
          token = $(echo ${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_PASSWORD }} | base64 -i -)
          curl -X POST $uploadUrl -H "Authorization: Bearer $token"
